name: Mirror Sync

on:
  push:
    branches:
      - main

jobs:
  sync-mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sync Mirror
        run: |
          sudo rsync -a --delete rsync://archive.ubuntu.com/ubuntu/ /var/www/html/ubuntu

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Sync mirror"
          git push origin main
